#!/bin/bash

cat /etc/collectd/collectd.conf.tmpl > /etc/collectd/collectd.conf

echo "
Hostname "$COLLECTD_LOCAL_HOSTNAME"

<Plugin write_graphite>
    <Carbon>
        Host "$COLLECTD_GRAPHITE_HOSTNAME"
        Port "2003"
    </Carbon>
</Plugin>
" >> /etc/collectd/collectd.conf

collectd -C /etc/collectd/collectd.conf -f
